# -*- coding: utf-8 -*-
"""Condições_Aninhadas27/09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPRWZUIzB6pXuSORUKmI3XAlou-RHqWH
"""

#Desafio 1-Escreva um programa para aprovar o empréstimo bancário para a compra
#de uma casa. O programa vai perguntar o valor da casa, o salário do comprador e
#em quantos anos ele vai pagar.
#Calcule o valor da prestação mensal, sanbendo que ela não pode exceder 30% do
#salário ou então empréstimo será negado.

valor_casa = float(input("Digite o valor do imovél: "))
salario = float(input("Informe o seu salário: "))
anos = int(input("Em quantos anos deseja pagar: "))

prestacao = valor_casa / (anos * 12)
if prestacao <= salario * 0.3:
    print("Empréstimo aprovado!")

else:
    print("Empréstimo negado!")

#Desafio 2-Escreva um programa que leia um número inteiro qualquer e peça para o
#usuário escolher qual será a base de conversão 1Binario 2 octal 3hexadecimal

numero = int(input("Escolha um número inteiro: "))
print("Escolha a base de conversão: ")
print("1 - Binário")
print("2 - Octal")
print("3 - Hexadecimal")
opção = int(input("Digite a opção desejada: "))

if opção == 1:
    print(bin(numero))

elif opção == 2:
    print(oct(numero))

elif opção == 3:
    print(hex(numero))

else:
    print("Número inválido!")

#Desafio 4-Faça um programa que leia o ano de nascimento de um jovem e informe,
#de acordo com sua idade: Se ele vai se alistar ao serviço militar. / Se é a hora
#de se alistar. / Se já passou do tempo de alistamento.
#Seu programa também deverá mostrar o tempo que falta ou que passou do prazo.

ano_nasc = int(input("Digite o ano de nascimento: "))
ano_atual = int(input("Digite o ano atual: "))

idade = ano_atual - ano_nasc
if idade < 18:
    print(f"Você ainda não tem 18 anos. Faltam {18 - idade} anos para se alistar.")

elif idade == 18:
    print("Você deve se alistar este ano!")

else:
    print(f"Você já passou do tempo de alistamento. Passaram {idade - 18} anos do prazo.")

#Desafio 5-Crie um programa que leia duas notas de um alune e calcule sua média
#mostranndo uma mensagem no final de acordo com a média atingida: Média abaixo
#DE 5.0: REPROVADO / Média entre 5.0 e 6.9: RECUPERAÇÃO / Média 7.0 ou superior:
#APROVADO

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))

media = (nota1 + nota2) / 2

if media < 5.0:
    print(f"Sua média é {media} infelizmente você foi: REPROVADO")

elif media >= 5.0 and media <= 6.9:
    print(f"Sua média é {media}: RECUPERAÇÃO")

else:
    print(f"Sua média é {media} você foi: APROVADO")

#Desafio 5-A confederação Nacional de Natação precisa de um programa que leia o
#ano de nascimento de um atleta e mostre sua categoria de acordo com a idade:
#até 9 anos: MIRIM / até 14 anos: INFANTIL/ até 19 anos: JUNIOR / até 20 anos:
#SENIOR / Acima: MASTER

ano_nasc = int(input("Digite o ano de nascimento: "))
ano_atual = int(input("Digite o ano atual: "))

idade = ano_atual - ano_nasc

if idade <= 9:
  print(f"Você tem {idade} anos e sua categoria é MIRIM")

elif idade <= 14:
  print(f"Você tem {idade} anos e sua categoria é INFANTIL")

elif idade <= 19:
  print(f"Você tem {idade} anos e sua categoria é JUNIOR")

elif idade <= 20:
  print(f"Você tem {idade} anos e sua categoria é SENIOR")

else:
  print(f"Você tem {idade} anos e sua categoria é MASTER")

#Desafio 6 -Elabore um programa que calcule o valor a ser pago por um produto,
#considerando o seu preço normal e condição de pagamento - à vista: 10% / Debito:
#5% / em ate 2x no cartão: preço formal / 3x ou mais no cartão 20% de juros.

produto = float(input("Informe o valor do produto "))
print("Escolha a forma de pagamento: ")
print("1 - à vista")
print("2 - Debito")
print("3 - em ate 2x no cartão")
print("4 - 3x ou mais no cartão")
opção = int(input("Digite a opção desejada: "))

if opção == 1:
    produto = produto - (produto * 0.1)
    print(f"O valor do produto com 10% de desconto é R${produto}")

elif opção == 2:
    produto = produto - (produto * 0.05)
    print(f"O valor do produto com 5% de desconto é R${produto}")

elif opção == 3:
    print(f"O valor do produto parcelado em 2x no cartão é R${produto}")

elif opção == 4:
    produto = produto + (produto * 0.2)
    print(f"O valor do produto parcelado em 3x ou mais, contém o acréscimo de 20% de juros e fica no total de R${produto}")

else:
    print("Opção inválida!")
